// Auto-generated by mclang — do not edit
'use strict';

let _addon;
try {
  _addon = require('./build/Release/geometry');
} catch {
  _addon = require('./build/Debug/geometry');
}

/** @type {(x1: number, y1: number, x2: number, y2: number) => number} */
exports.dist2d = _addon.dist2d;
/** @type {(x1: number, y1: number, x2: number, y2: number) => number} */
exports.angle2d = _addon.angle2d;
/** @type {(ax: number, ay: number, bx: number, by: number, cx: number, cy: number) => number} */
exports.triangle_area = _addon.triangle_area;
/** @type {(v: Float64Array, w: Float64Array) => number} */
exports.dot3 = _addon.dot3;
/** @type {(v: Float64Array, w: Float64Array) => Float64Array} */
exports.cross3 = _addon.cross3;
/** @type {(v: Float64Array) => number} */
exports.len3 = _addon.len3;
/** @type {(m: Float64Array, m_rows: number, m_cols: number, j: number, outSize: number) => Float64Array} */
exports.matrix_col = _addon.matrix_col;
/** @type {(m: Float64Array, m_rows: number, m_cols: number, i: number, outSize: number) => Float64Array} */
exports.matrix_row = _addon.matrix_row;

// Re-export all
Object.assign(exports, _addon);
