// Auto-generated by mclang — do not edit
//
// Cargo.toml:
//   [build-dependencies]
//   cc = "1"
//
// build.rs:
//   fn main() {
//       cc::Build::new().file("geometry.c").compile("geometry");
//   }

#[allow(non_snake_case, dead_code)]
unsafe extern "C" {
    pub fn dist2d(x1: f64, y1: f64, x2: f64, y2: f64) -> f64;
    pub fn angle2d(x1: f64, y1: f64, x2: f64, y2: f64) -> f64;
    pub fn triangle_area(ax: f64, ay: f64, bx: f64, by: f64, cx: f64, cy: f64) -> f64;
    pub fn dot3(v: *const f64, v_len: i32, w: *const f64, w_len: i32) -> f64;
    pub fn cross3(v: *const f64, v_len: i32, w: *const f64, w_len: i32) -> *const f64;
    pub fn len3(v: *const f64, v_len: i32) -> f64;
    pub fn matrix_col(m: *const f64, m_rows: i32, m_cols: i32, j: i32) -> *const f64;
    pub fn matrix_row(m: *const f64, m_rows: i32, m_cols: i32, i: i32) -> *const f64;
}
