// Auto-generated by mclang — do not edit
//
// Cargo.toml:
//   [build-dependencies]
//   cc = "1"
//
// build.rs:
//   fn main() {
//       cc::Build::new().file("math.c").compile("math");
//   }

#[allow(non_snake_case, dead_code)]
unsafe extern "C" {
    pub fn s2__area(r: f64) -> f64;
    pub fn s2__perimeter(r: f64) -> f64;
    pub fn s2__rect_area(w: f64, h: f64) -> f64;
    pub fn s2__rect_perimeter(w: f64, h: f64) -> f64;
    pub fn s2__tri_area(a: f64, b: f64, c: f64) -> f64;
    pub fn s3__area(r: f64) -> f64;
    pub fn s3__volume(r: f64) -> f64;
    pub fn s3__cube_area(a: f64) -> f64;
    pub fn s3__cube_volume(a: f64) -> f64;
    pub fn s3__cyl_area(r: f64, h: f64) -> f64;
    pub fn s3__cyl_volume(r: f64, h: f64) -> f64;
}
