// Auto-generated by mclang — do not edit
'use strict';

let _addon;
try {
  _addon = require('./build/Release/math');
} catch {
  _addon = require('./build/Debug/math');
}

/** @type {(r: number) => number} */
exports.s2__area = _addon.s2__area;
/** @type {(r: number) => number} */
exports.s2__perimeter = _addon.s2__perimeter;
/** @type {(w: number, h: number) => number} */
exports.s2__rect_area = _addon.s2__rect_area;
/** @type {(w: number, h: number) => number} */
exports.s2__rect_perimeter = _addon.s2__rect_perimeter;
/** @type {(a: number, b: number, c: number) => number} */
exports.s2__tri_area = _addon.s2__tri_area;
/** @type {(r: number) => number} */
exports.s3__area = _addon.s3__area;
/** @type {(r: number) => number} */
exports.s3__volume = _addon.s3__volume;
/** @type {(a: number) => number} */
exports.s3__cube_area = _addon.s3__cube_area;
/** @type {(a: number) => number} */
exports.s3__cube_volume = _addon.s3__cube_volume;
/** @type {(r: number, h: number) => number} */
exports.s3__cyl_area = _addon.s3__cyl_area;
/** @type {(r: number, h: number) => number} */
exports.s3__cyl_volume = _addon.s3__cyl_volume;

// Re-export all
Object.assign(exports, _addon);
