// Auto-generated by mclang — do not edit
//
// Cargo.toml:
//   [build-dependencies]
//   cc = "1"
//
// build.rs:
//   fn main() {
//       cc::Build::new().file("ballistics.c").compile("ballistics");
//   }

#[allow(non_snake_case, dead_code)]
unsafe extern "C" {
    pub fn range(v0: f64, angle: f64) -> f64;
    pub fn max_height(v0: f64, angle: f64) -> f64;
    pub fn time_of_flight(v0: f64, angle: f64) -> f64;
    pub fn height_at(v0: f64, angle: f64, x: f64) -> f64;
}
