// Auto-generated by mclang — do not edit
'use strict';

let _addon;
try {
  _addon = require('./build/Release/ballistics');
} catch {
  _addon = require('./build/Debug/ballistics');
}

/** @type {(v0: number, angle: number) => number} */
exports.range = _addon.range;
/** @type {(v0: number, angle: number) => number} */
exports.max_height = _addon.max_height;
/** @type {(v0: number, angle: number) => number} */
exports.time_of_flight = _addon.time_of_flight;
/** @type {(v0: number, angle: number, x: number) => number} */
exports.height_at = _addon.height_at;

// Re-export all
Object.assign(exports, _addon);
