// Auto-generated by mclang — do not edit
'use strict';

let _addon;
try {
  _addon = require('./build/Release/number_theory');
} catch {
  _addon = require('./build/Debug/number_theory');
}

/** @type {(a: number, b: number) => number} */
exports.gcd = _addon.gcd;
/** @type {(a: number, b: number) => number} */
exports.lcm = _addon.lcm;
/** @type {(n: number) => number} */
exports.is_even = _addon.is_even;
/** @type {(n: number) => number} */
exports.is_odd = _addon.is_odd;
/** @type {(n: number, d: number) => number} */
exports.is_divisible = _addon.is_divisible;
/** @type {(x: number) => number} */
exports.is_integer = _addon.is_integer;
/** @type {(x: number) => number} */
exports.is_natural = _addon.is_natural;
/** @type {(n: number) => number} */
exports.triangular = _addon.triangular;
/** @type {(n: number) => number} */
exports.digital_root = _addon.digital_root;

// Re-export all
Object.assign(exports, _addon);
