// Auto-generated by mclang — do not edit
//
// Cargo.toml:
//   [build-dependencies]
//   cc = "1"
//
// build.rs:
//   fn main() {
//       cc::Build::new().file("number_theory.c").compile("number_theory");
//   }

#[allow(non_snake_case, dead_code)]
unsafe extern "C" {
    pub fn gcd(a: f64, b: f64) -> f64;
    pub fn lcm(a: f64, b: f64) -> f64;
    pub fn is_even(n: f64) -> f64;
    pub fn is_odd(n: f64) -> f64;
    pub fn is_divisible(n: f64, d: f64) -> f64;
    pub fn is_integer(x: f64) -> f64;
    pub fn is_natural(x: f64) -> f64;
    pub fn triangular(n: f64) -> f64;
    pub fn digital_root(n: f64) -> f64;
}
