import type { File, FuncDef, Param, McType } from '../ast/nodes.js';
import type { CgenPrecision } from './codegen.js';

// ── Type mapping ──────────────────────────────────────────────────────────────

function rustNumType(precision: CgenPrecision): string {
  if (precision === 'f32') return 'f32';
  if (precision === 'fixed') return 'i16';
  return 'f64';
}

function isArray(ty: McType | undefined): boolean {
  return ty?.kind === 'NumType' && (ty.dims ?? 0) === 1;
}

function isMatrix(ty: McType | undefined): boolean {
  return ty?.kind === 'NumType' && (ty.dims ?? 0) >= 2;
}

// Returns list of "name: RustType" strings for one mclang param
function rustParams(p: Param, num: string): string[] {
  const name = safeIdent(p.name);
  const ty = p.type;
  if (isMatrix(ty)) {
    return [`${name}: *const ${num}`, `${name}_rows: i32`, `${name}_cols: i32`];
  }
  if (isArray(ty)) {
    return [`${name}: *const ${num}`, `${name}_len: i32`];
  }
  if (ty?.kind === 'IntType') return [`${name}: i32`];
  return [`${name}: ${num}`];
}

// Rust-safe identifier (translit already handles ASCII; add _ prefix for keywords)
const RUST_KEYWORDS = new Set([
  'as', 'break', 'const', 'continue', 'crate', 'else', 'enum', 'extern',
  'false', 'fn', 'for', 'if', 'impl', 'in', 'let', 'loop', 'match', 'mod',
  'move', 'mut', 'pub', 'ref', 'return', 'self', 'Self', 'static', 'struct',
  'super', 'trait', 'true', 'type', 'unsafe', 'use', 'where', 'while',
]);

function safeIdent(name: string): string {
  // translit is not imported here — names from AST are already ASCII after parser
  const safe = name.replace(/[^a-zA-Z0-9_]/g, '_');
  return RUST_KEYWORDS.has(safe) ? `r#${safe}` : safe;
}

// ── Main generator ────────────────────────────────────────────────────────────

export function generateRust(ast: File, baseName: string, precision: CgenPrecision = 'f64'): string {
  const num = rustNumType(precision);
  const lines: string[] = [];

  lines.push(`// Auto-generated by mclang — do not edit`);
  lines.push(`//`);
  lines.push(`// Cargo.toml:`);
  lines.push(`//   [build-dependencies]`);
  lines.push(`//   cc = "1"`);
  lines.push(`//`);
  lines.push(`// build.rs:`);
  lines.push(`//   fn main() {`);
  lines.push(`//       cc::Build::new().file("${baseName}.c").compile("${baseName}");`);
  lines.push(`//   }`);
  lines.push(``);
  lines.push(`#[allow(non_snake_case, dead_code)]`);
  lines.push(`unsafe extern "C" {`);

  for (const node of ast.body) {
    if (node.kind !== 'FuncDef') continue;
    if (node.name.startsWith('_')) continue; // private

    const hasDefaults = node.params.some(p => p.default !== undefined);
    const cName = safeIdent(node.name);

    if (hasDefaults) {
      // Expose _impl (all params required) + each wrapper
      emitDefaultsVariants(lines, node, cName, num, precision);
    } else {
      emitSimpleFunc(lines, node, cName, num);
    }
  }

  lines.push(`}`);
  return lines.join('\n') + '\n';
}

function emitSimpleFunc(lines: string[], node: FuncDef, cName: string, num: string): void {
  const params = node.params.flatMap(p => rustParams(p, num));
  const paramStr = params.length > 0 ? params.join(', ') : '';
  const ret = funcReturnType(node, num);
  lines.push(`    pub fn ${cName}(${paramStr}) -> ${ret};`);
}

function emitDefaultsVariants(lines: string[], node: FuncDef, cName: string, num: string, _precision: CgenPrecision): void {
  const params = node.params;
  const total = params.length;
  const reqCount = params.findIndex(p => p.default !== undefined);
  const defaultCount = total - reqCount;
  const ret = funcReturnType(node, num);

  // _impl — all params explicit
  const allParams = params.flatMap(p => rustParams(p, num));
  lines.push(`    // ${cName} has ${defaultCount} optional param(s) — use _impl for full control`);
  lines.push(`    pub fn _${cName}_impl(${allParams.join(', ')}) -> ${ret};`);

  // wrapper variants _d1 … _dN (fewer params)
  for (let d = 1; d <= defaultCount; d++) {
    const provided = total - d;
    const wName = `_${cName}_d${d}`;
    const wParams = params.slice(0, provided).flatMap(p => rustParams(p, num));
    lines.push(`    pub fn ${wName}(${wParams.join(', ')}) -> ${ret};`);
  }
}

// Mirror of CGenerator.exprReturnsPtr
const ARRAY_RETURNING_FNS = new Set([
  'cross', 'transpose', 'inv', 'I', 'zeros', 'ones',
]);

function exprReturnsPtr(expr: { kind: string; name?: string }): boolean {
  switch (expr.kind) {
    case 'MatrixSlice': return true;
    case 'SliceExpr':   return true;
    case 'PmExpr':      return true;
    case 'ArrayLit':    return true;
    case 'FuncCallExpr': return ARRAY_RETURNING_FNS.has(expr.name ?? '');
    default: return false;
  }
}

function funcReturnType(node: FuncDef, num: string): string {
  const last = node.body[node.body.length - 1];
  if (last?.kind === 'ExprStmt' && exprReturnsPtr(last.expr)) {
    return `*const ${num}`;
  }
  return num;
}
