// Auto-generated by mclang — do not edit
'use strict';

let _addon;
try {
  _addon = require('./build/Release/statistics');
} catch {
  _addon = require('./build/Debug/statistics');
}

/** @type {(v: Float64Array) => number} */
exports.avg = _addon.avg;
/** @type {(v: Float64Array) => number} */
exports.spread = _addon.spread;
/** @type {(v: Float64Array) => number} */
exports.cv = _addon.cv;
/** @type {(v: Float64Array) => number} */
exports.data_range = _addon.data_range;
/** @type {(v: Float64Array, x: number) => number} */
exports.z_score = _addon.z_score;
/** @type {(v: Float64Array, x: number) => number} */
exports.normalize = _addon.normalize;

// Re-export all
Object.assign(exports, _addon);
