// Auto-generated by mclang — do not edit
//
// Cargo.toml:
//   [build-dependencies]
//   cc = "1"
//
// build.rs:
//   fn main() {
//       cc::Build::new().file("statistics.c").compile("statistics");
//   }

#[allow(non_snake_case, dead_code)]
unsafe extern "C" {
    pub fn avg(v: *const f64, v_len: i32) -> f64;
    pub fn spread(v: *const f64, v_len: i32) -> f64;
    pub fn cv(v: *const f64, v_len: i32) -> f64;
    pub fn data_range(v: *const f64, v_len: i32) -> f64;
    pub fn z_score(v: *const f64, v_len: i32, x: f64) -> f64;
    pub fn normalize(v: *const f64, v_len: i32, x: f64) -> f64;
}
